Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,81 +1,125 @@
 language: generic
-sudo: false
 git:
   depth: 10
 
-matrix:
-  include:
-    - os: linux
-      env:
-        - VIM_VERSION=v7.4
-    - os: linux
-      env:
-        - VIM_VERSION=v8.0.0000
-    - os: linux
-      env:
-        - VIM_VERSION=master
-    - os: osx
-
-addons:
-  apt:
-    packages:
-      - language-pack-ja
-      - vim
-      - libperl-dev
-      - python-dev
-      - python3-dev
-      - ruby-dev
-      - liblua5.1-0-dev
-      - lua5.1
-  homebrew:
-    packages:
-      - macvim
-
 cache:
   directories:
-    - /tmp/vim
+    - $HOME/cache
 
-install:
-  - rvm reset
-  - |
-    case "${TRAVIS_OS_NAME}" in
-      linux)
-        need_build=0
-        if [[ ! -d "/tmp/vim/${VIM_VERSION}" ]]; then
-          git clone --depth 1 --branch "${VIM_VERSION}" --single-branch https://github.com/vim/vim "/tmp/vim/${VIM_VERSION}"
-          need_build=1
-        fi
-        if [[ ! -f "/tmp/vim/${VIM_VERSION}/build/vim" ]]; then
-          need_build=1
-        fi
-        if [[ "${VIM_VERSION}" = "master" && "${need_build}" = "1" ]]; then
-          cd "/tmp/vim/${VIM_VERSION}"
-          git fetch
-          if ! git diff --exit-code --quiet ..origin/master; then
-            git reset --hard origin/master
-            git clean -dfx
-            need_build=1
+before_install:
+  - mkdir -p ${HOME}/cache
+
+anchors:
+  linux: &linux
+    os: linux
+    dist: xenial
+    install:
+      - docker pull "thinca/vim:${VIM_VERSION}"
+    script:
+      - docker run --rm -it "thinca/vim:${VIM_VERSION}" --version
+      - docker run --rm -it -v "${PWD}:/root" --entrypoint bin/themis "thinca/vim:${VIM_VERSION}" --reporter dot
+  osx: &osx
+    os: osx
+    install:
+      - |
+        if [[ ${VIM_VERSION} = 'latest' ]]; then
+          VIM_URL=$(curl -s --retry 3 'https://vim-jp.org/redirects/macvim-dev/macvim/latest.json' | sed 's@.*"redirect_url":"\([^"]*\)".*@\1@')
+          if [[ -z "${VIM_URL}" ]]; then
+            echo "Can't get Vim's URL" >&2
+            exit 64
+          fi
+          VIM_VERSION=$(echo ${VIM_URL} | sed 's@.*/download/\([^/]*\).*@\1@')
+          if [[ -z "${VIM_VERSION}" ]]; then
+            echo "Can't detect Vim's version from URL(${VIM_URL})" >&2
+            exit 65
           fi
         fi
-        if [[ "${need_build}" = "1" ]]; then
-          cd "/tmp/vim/${VIM_VERSION}"
-          ./configure --prefix="/tmp/vim/${VIM_VERSION}/build" --with-features=huge \
-            --enable-perlinterp --enable-pythoninterp --enable-python3interp \
-            --enable-rubyinterp --enable-luainterp --enable-fail-if-missing
-          make -j2
-          make install
+      - |
+        if [[ ! -d "${HOME}/cache/macvim-${VIM_VERSION}" ]]; then
+          echo "Download from ${VIM_URL}"
+          curl --silent --location --output "/tmp/MacVim.dmg" "${VIM_URL}"
+          hdiutil attach -quiet -mountpoint "/Volumes/MacVim" "/tmp/MacVim.dmg"
+          mkdir -p "${HOME}/cache/macvim-${VIM_VERSION}"
+          cp -r "/Volumes/MacVim/MacVim.app" "${HOME}/cache/macvim-${VIM_VERSION}"
+          hdiutil detach "/Volumes/MacVim"
+          rm "/tmp/MacVim.dmg"
         fi
-        cd "${TRAVIS_BUILD_DIR}"
-        export PATH=/tmp/vim/${VIM_VERSION}/build/bin:${PATH}
-      ;;
-      osx)
-      ;;
-      *)
-        echo "Unknown value of \${TRAVIS_OS_NAME}: ${TRAVIS_OS_NAME}"
-        exit 65
-      ;;
-    esac
+      - |
+        if [[ -x "${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/bin/vim" ]]; then
+          export THEMIS_VIM="${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/bin/vim"
+        elif [[ -x "${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/MacOS/Vim" ]]; then
+          export THEMIS_VIM="${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/MacOS/Vim"
+        fi
+    script:
+      - ${THEMIS_VIM} --version
+      - ./bin/themis --reporter dot
+  windows: &windows
+    os: windows
+    language: c  # 'generic' is not supported yet on windows
+    install:
+      - |
+        if [[ ${VIM_VERSION} = 'latest' ]]; then
+          VIM_URL=$(curl -s --retry 3 'https://vim-jp.org/redirects/vim/vim-win32-installer/latest/x64.json' | jq -r '.redirect_url')
+          if [[ -z "${VIM_URL}" ]]; then
+            echo "Can't get Vim's URL" >&2
+            exit 64
+          fi
+          VIM_VERSION=$(echo ${VIM_URL} | sed 's@.*/download/\([^/]*\).*@\1@')
+          if [[ -z "${VIM_VERSION}" ]]; then
+            echo "Can't detect Vim's version from URL(${VIM_URL})" >&2
+            exit 65
+          fi
+        fi
+      - |
+        if [[ ! -d ${HOME}/cache/vim-${VIM_VERSION} ]]; then
+          if [[ -z "${VIM_URL}" ]]; then
+            if [[ "${VIM_VERSION}" =~ "v7" ]]; then
+              VIM_URL=https://ftp.nluug.nl/pub/vim/pc/vim$(echo ${VIM_VERSION} | sed 's/[^0-9]//g')w32.zip
+            else
+              VIM_URL=https://github.com/vim/vim-win32-installer/releases/download/${VIM_VERSION}/gvim_$(echo ${VIM_VERSION} | sed 's/v//')_x64.zip
+            fi
+          fi
+          echo "Download from ${VIM_URL}"
+          curl --silent --location --output "${HOME}/cache/vim-${VIM_VERSION}.zip" "${VIM_URL}"
+          7z x "-o${HOME}/cache/vim-${VIM_VERSION}" "${HOME}/cache/vim-${VIM_VERSION}.zip"
+          rm "${HOME}/cache/vim-${VIM_VERSION}.zip"
+        fi
+      - export THEMIS_VIM=$(echo ${HOME}/cache/vim-${VIM_VERSION}/vim/*/vim.exe)
+    script:
+      - ${THEMIS_VIM} --version
+      - ./bin/themis.bat --reporter dot
 
-script:
-  - vim --version
-  - ./bin/themis --reporter dot
+jobs:
+  include:
+    - <<: *linux
+      env: VIM_VERSION=v7.4
+    - <<: *linux
+      env: VIM_VERSION=v8.0.0000
+    - <<: *linux
+      env: VIM_VERSION=v8.1.0005
+    - <<: *linux
+      env: VIM_VERSION=latest
+    - <<: *osx
+      env:
+        - VIM_VERSION=v7.4.903
+        - VIM_URL=https://github.com/macvim-dev/macvim/releases/download/snapshot-79/MacVim-7.4.dmg
+    - <<: *osx
+      env:
+        - VIM_VERSION=v8.0.0003
+        - VIM_URL=https://github.com/macvim-dev/macvim/releases/download/snapshot-110/MacVim.dmg
+    - <<: *osx
+      env:
+        - VIM_VERSION=v8.1.0039
+        - VIM_URL=https://github.com/macvim-dev/macvim/releases/download/snapshot-148/MacVim.dmg
+    - <<: *osx
+      env: VIM_VERSION=latest
+    - <<: *windows
+      env: VIM_VERSION=v7.3
+    - <<: *windows
+      env: VIM_VERSION=v7.4
+    - <<: *windows
+      env: VIM_VERSION=v8.0.0003
+    - <<: *windows
+      env: VIM_VERSION=v8.1.0001
+    - <<: *windows
+      env: VIM_VERSION=latest
diff --git a/examples/ci/.travis.yml b/examples/ci/.travis.yml
--- a/examples/ci/.travis.yml
+++ b/examples/ci/.travis.yml
@@ -1,58 +1,130 @@
 language: generic
+git:
+  depth: 10
 
 env:
-  - HEAD=yes
-  - HEAD=no
-
-sudo: false
-
-addons:
-  apt:
-    packages:
-      - language-pack-ja
-      - vim
-      - libperl-dev
-      - python-dev
-      - python3-dev
-      - liblua5.1-0-dev
-      - lua5.1
+  global:
+    - THEMIS_VERSION=v1.5.4
 
 cache:
   directories:
-    - /tmp/vim
+    - $HOME/cache
 
-install:
-  - |
-    if [ x"${HEAD}" = "xyes" ]; then
-      if [ -d /tmp/vim/.git ]; then
-        cd /tmp/vim
-        git fetch
-        if git diff --exit-code --quiet ..origin/master; then
-          need_build=0
-        else
-          git reset --hard origin/master
-          git clean -dfx
-          need_build=1
+before_install:
+  - mkdir -p ${HOME}/cache
+  - '[[ -d ${HOME}/cache/themis-${THEMIS_VERSION} ]] || git clone --depth 1 --branch ${THEMIS_VERSION} --single-branch https://github.com/thinca/vim-themis ${HOME}/cache/themis-${THEMIS_VERSION}'
+
+anchors:
+  linux: &linux
+    os: linux
+    dist: xenial
+    install:
+      - docker pull "thinca/vim:${VIM_VERSION}"
+    script:
+      - docker run --rm -it "thinca/vim:${VIM_VERSION}" --version
+      - docker run --rm -it -v "${PWD}:/root" -v "${HOME}/cache/themis-${THEMIS_VERSION}:/tmp/themis" --entrypoint /tmp/themis/bin/themis "thinca/vim:${VIM_VERSION}" --reporter dot
+  osx: &osx
+    os: osx
+    install:
+      - |
+        if [[ ${VIM_VERSION} = 'latest' ]]; then
+          VIM_URL=$(curl -s --retry 3 'https://vim-jp.org/redirects/macvim-dev/macvim/latest.json' | sed 's@.*"redirect_url":"\([^"]*\)".*@\1@')
+          if [[ -z "${VIM_URL}" ]]; then
+            echo "Can't get Vim's URL" >&2
+            exit 64
+          fi
+          VIM_VERSION=$(echo ${VIM_URL} | sed 's@.*/download/\([^/]*\).*@\1@')
+          if [[ -z "${VIM_VERSION}" ]]; then
+            echo "Can't detect Vim's version from URL(${VIM_URL})" >&2
+            exit 65
+          fi
         fi
-      else
-        git clone --depth 1 --single-branch https://github.com/vim/vim /tmp/vim
-        cd /tmp/vim
-        need_build=1
-      fi
-      if [ "${need_build}" = "1" ]; then
-        ./configure --prefix="$PWD/build" --with-features=huge \
-          --enable-perlinterp --enable-pythoninterp --enable-python3interp \
-          --enable-rubyinterp --enable-luainterp --enable-fail-if-missing
-        make -j2
-        make install
-      fi
-      export PATH=$PWD/build/bin:$PATH
-      cd "${TRAVIS_BUILD_DIR}"
-    fi
+      - |
+        if [[ ! -d "${HOME}/cache/macvim-${VIM_VERSION}" ]]; then
+          echo "Download from ${VIM_URL}"
+          curl --silent --location --output "/tmp/MacVim.dmg" "${VIM_URL}"
+          hdiutil attach -quiet -mountpoint "/Volumes/MacVim" "/tmp/MacVim.dmg"
+          mkdir -p "${HOME}/cache/macvim-${VIM_VERSION}"
+          cp -r "/Volumes/MacVim/MacVim.app" "${HOME}/cache/macvim-${VIM_VERSION}"
+          hdiutil detach "/Volumes/MacVim"
+          rm "/tmp/MacVim.dmg"
+        fi
+      - |
+        if [[ -x "${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/bin/vim" ]]; then
+          export THEMIS_VIM="${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/bin/vim"
+        elif [[ -x "${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/MacOS/Vim" ]]; then
+          export THEMIS_VIM="${HOME}/cache/macvim-${VIM_VERSION}/MacVim.app/Contents/MacOS/Vim"
+        fi
+    script:
+      - ${THEMIS_VIM} --version
+      - ${HOME}/cache/themis-${THEMIS_VERSION}/bin/themis --reporter dot
+  windows: &windows
+    os: windows
+    language: c  # 'generic' is not supported yet on windows
+    install:
+      - |
+        if [[ ${VIM_VERSION} = 'latest' ]]; then
+          VIM_URL=$(curl -s --retry 3 'https://vim-jp.org/redirects/vim/vim-win32-installer/latest/x64.json' | jq -r '.redirect_url')
+          if [[ -z "${VIM_URL}" ]]; then
+            echo "Can't get Vim's URL" >&2
+            exit 64
+          fi
+          VIM_VERSION=$(echo ${VIM_URL} | sed 's@.*/download/\([^/]*\).*@\1@')
+          if [[ -z "${VIM_VERSION}" ]]; then
+            echo "Can't detect Vim's version from URL(${VIM_URL})" >&2
+            exit 65
+          fi
+        fi
+      - |
+        if [[ ! -d ${HOME}/cache/vim-${VIM_VERSION} ]]; then
+          if [[ -z "${VIM_URL}" ]]; then
+            if [[ "${VIM_VERSION}" =~ "v7" ]]; then
+              VIM_URL=https://ftp.nluug.nl/pub/vim/pc/vim$(echo ${VIM_VERSION} | sed 's/[^0-9]//g')w32.zip
+            else
+              VIM_URL=https://github.com/vim/vim-win32-installer/releases/download/${VIM_VERSION}/gvim_$(echo ${VIM_VERSION} | sed 's/v//')_x64.zip
+            fi
+          fi
+          echo "Download from ${VIM_URL}"
+          curl --silent --location --output "${HOME}/cache/vim-${VIM_VERSION}.zip" "${VIM_URL}"
+          7z x "-o${HOME}/cache/vim-${VIM_VERSION}" "${HOME}/cache/vim-${VIM_VERSION}.zip"
+          rm "${HOME}/cache/vim-${VIM_VERSION}.zip"
+        fi
+      - export THEMIS_VIM=$(echo ${HOME}/cache/vim-${VIM_VERSION}/vim/*/vim.exe)
+    script:
+      - ${THEMIS_VIM} --version
+      - ${HOME}/cache/themis-${THEMIS_VERSION}/bin/themis.bat --reporter dot
 
-before_script:
-  - git clone https://github.com/thinca/vim-themis --quiet --branch v1.5.4 --single-branch --depth 1 /tmp/vim-themis
-
-script:
-  - vim --version
-  - /tmp/vim-themis/bin/themis --reporter dot
+jobs:
+  include:
+    - <<: *linux
+      env: VIM_VERSION=v7.4
+    - <<: *linux
+      env: VIM_VERSION=v8.0.0000
+    - <<: *linux
+      env: VIM_VERSION=v8.1.0005
+    - <<: *linux
+      env: VIM_VERSION=latest
+    - <<: *osx
+      env:
+        - VIM_VERSION=v7.4.903
+        - VIM_URL=https://github.com/macvim-dev/macvim/releases/download/snapshot-79/MacVim-7.4.dmg
+    - <<: *osx
+      env:
+        - VIM_VERSION=v8.0.0003
+        - VIM_URL=https://github.com/macvim-dev/macvim/releases/download/snapshot-110/MacVim.dmg
+    - <<: *osx
+      env:
+        - VIM_VERSION=v8.1.0039
+        - VIM_URL=https://github.com/macvim-dev/macvim/releases/download/snapshot-148/MacVim.dmg
+    - <<: *osx
+      env: VIM_VERSION=latest
+    - <<: *windows
+      env: VIM_VERSION=v7.3
+    - <<: *windows
+      env: VIM_VERSION=v7.4
+    - <<: *windows
+      env: VIM_VERSION=v8.0.0003
+    - <<: *windows
+      env: VIM_VERSION=v8.1.0001
+    - <<: *windows
+      env: VIM_VERSION=latest
